# Pywal Colors 
include ~/.cache/wal/colors-kitty.conf

# Font Settings
font_family      Iosevka 
font_size        11

# Fish Shell
shell  fish

# Mouse & Cursor
cursor_shape     block
cursor_blink_interval 0
url_style        curly

# Window Layout
remember_window_size  no
initial_window_width  78c
initial_window_height 23c
window_padding_width  15

# Background & Opacity (Crucial for blur)
background_opacity 0.80

# Performance
sync_to_monitor yes
repaint_delay 8
input_delay 3

# Extra Visuals
cursor_trail 3
confirm_os_window_close 0

