general {
    lock_cmd = /usr/bin/hyprlock
    before_sleep_cmd = /usr/bin/hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 3 MINUTES: LOCK
listener {
    timeout = 180
    on-timeout = /usr/bin/hyprlock
}

# 5 MINUTES: SCREEN OFF
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}


# 30 MINUTES: SUSPEND
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
