#source Files 
source = ~/.config/sources/monitors.conf
source = ~/.config/sources/auto_start.conf
source = ~/.config/sources/env_variables.conf
source = ~/.config/sources/keyBindings.conf
source = ~/.config/sources/LookandFeel.conf
source = ~/.config/sources/Input.conf
source = ~/.config/sources/Animations.conf
source = ~/.config/sources/WindowRules.conf
source = ~/.config/sources/Layout.conf
source = ~/.config/sources/Misc.conf
source = ~/.config/sources/LayersRule.conf



