[Appearance]
color_scheme_path=~/.config/qt5ct/colors/matugen.conf
custom_palette=true

color_scheme_path=~/.local/share/color-schemes/Matugen.colors
custom_palette=true
icon_theme=breeze
style=Darkly
