[ColorEffects:Disabled]
Color=#13140d
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=#47483b
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=#1b1c15
BackgroundNormal=#2a2b22
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:Complementary]
BackgroundAlternate=#1b1c15
BackgroundNormal=#13140d
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#deea96
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:Header]
BackgroundAlternate=#13140d
BackgroundNormal=#1f2018
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:Header][Inactive]
BackgroundAlternate=#1f2018
BackgroundNormal=#1f2018
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:Selection]
BackgroundAlternate=#1b1c15
BackgroundNormal=#c2cd7c
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#2d3400
ForegroundInactive=#c8c7b7
ForegroundLink=#e2e5c2
ForegroundNegative=#93000a
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e2e5c2
ForegroundPositive=#224e44
ForegroundVisited=#e2e5c2

[Colors:Tooltip]
BackgroundAlternate=#13140d
BackgroundNormal=#1f2018
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:View]
BackgroundAlternate=#1f2018
BackgroundNormal=#13140d
DecorationFocus=#424b06
DecorationHover=#2d3400
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[Colors:Window]
BackgroundAlternate=#424b06
BackgroundNormal=#1f2018
DecorationFocus=#c2cd7c
DecorationHover=#c2cd7c
ForegroundActive=#c2cd7c
ForegroundInactive=#c8c7b7
ForegroundLink=#c6c9a7
ForegroundNegative=#ffb4ab
ForegroundNeutral=#a2d0c2
ForegroundNormal=#e4e3d6
ForegroundPositive=#bdecde
ForegroundVisited=#e2e5c2

[General]
ColorScheme=Matugen
Name=Matugen

[Appearance]
color_scheme=Matugen

[KDE]
contrast=4

[WM]
activeBackground=#424b06
activeBlend=#deea96
activeForeground=#deea96
inactiveBackground=#13140d
inactiveBlend=#c8c7b7
inactiveForeground=#c8c7b7

