#AUTO START

exec-once = waybar 
exec-once = awww-daemon &
exec-once = swaync
exec-once = ~/.config/waybar/scripts/launch.sh

exec-once = hypridle  # Starting Hypridle To Detect Movements

exec-once = numlockx on  # Automatically Numlock On

exec-once = fish ~/.config/hypr/scripts/wob-start.fish 

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular


exec-once = eww daemon &    # Eww daemon (prevents slow initial startup)

exec-once = swayosd-server &   # SwayOSD server


exec-once = $HOME/.config/eww/visualizer/scripts/audio_monitor.sh &     # Visualizer Audio Monitor
