# Hyprland Layer Rules
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5

layerrule = match:namespace sidebar, blur on
layerrule = match:namespace sidebar, ignore_alpha 0.5

layerrule = match:namespace visualizer_win, blur on
layerrule = match:namespace visualizer_win, ignore_alpha 0.5
