
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# Floating constraints for Waybar/SwayNC Popups
windowrule {
    name = floating-impala
    match:class = ^(floating_impala)$

    float = yes
    size = 800 600
    center = yes
}

windowrule {
    name = floating-bluetui
    match:class = ^(floating_bluetui)$

    float = yes
    size = 800 600
    center = yes
}

windowrule {
    name = floating-btop
    match:class = ^(floating_btop)$

    float = yes
    size = 900 700
    center = yes
}

windowrule {
    name = floating-fastfetch
    match:class = ^(floating_fastfetch)$

    float = yes
    size = 800 500
    center = yes
}

windowrule {
    name = floating-wiremix
    match:class = ^(floating_wiremix)$

    float = yes
    size = 900 600
    center = yes
}


windowrule {
    name = screensaver
    match:class = ^(Screensaver)$
    fullscreen = yes
    no_anim = on
}


# Calculator Window Rule
windowrule {
    name = floating-calculator
    # Matches most common calculator apps (Gnome, GTK, etc.)
    match:class = ^(org.gnome.Calculator|galculator|kcalc|calculator)$

    float = yes
    size = 360 520
    center = yes
}

# Satty (Screenshot Editor) Window Rule
windowrule {
    name = floating-satty
    match:class = ^(com.gabm.satty)$

    float = yes
    size = 900 800
    center = yes
}